site_name: DID-Python
theme:
  name: material
nav:
    - Home: index.md
    - API Reference: api.md
    - Database: database.md
    - Document: document.md
    - SQLiteDB: sqlitedb.md
    - Query: query.md
    - Functions: fun.md
